# Generated by Django 3.1.3 on 2020-11-11 21:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('specifications', models.TextField(blank=True, help_text='Especificaciones de la tarea', null=True, verbose_name='Especificaciones')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas estimadas')),
                ('status', models.CharField(choices=[('0', 'Creada'), ('1', 'Asignada'), ('2', 'En proceso'), ('3', 'En revisión'), ('4', 'Finalizada')], max_length=1, verbose_name='Estado')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
