# Generated by Django 3.1.3 on 2020-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201112_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivo del cambio de estado de la tarea', null=True, verbose_name='Motivo'),
        ),
    ]
