# Generated by Django 3.1.3 on 2020-11-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
